# Generated by Django 3.1.5 on 2021-01-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title1', models.CharField(max_length=1000)),
                ('title2', models.CharField(max_length=1000)),
                ('title3', models.CharField(max_length=1000)),
                ('title4', models.CharField(max_length=1000)),
                ('title5', models.CharField(max_length=1000)),
                ('title6', models.CharField(max_length=1000)),
                ('title7', models.CharField(max_length=1000)),
                ('title8', models.CharField(max_length=1000)),
                ('title9', models.CharField(max_length=1000)),
                ('title10', models.CharField(max_length=1000)),
            ],
        ),
    ]
